[tools]
age = "latest"
bun = "latest"
cheat = "latest"
claude = "latest"
clojure = "latest"
deno = "latest"
fzf = "latest"
git-cliff = "latest"
gitu = "latest"
helix = "latest"
java = "oracle-graalvm"
node = "lts"
postgres = "17"
python = "3.14"
ripgrep = "latest"
rust = "stable"
sops = "latest"
zellij = "latest"
zig = "latest"
zigmod = "latest"
zls = "latest"

[settings]
idiomatic_version_file_enable_tools = []
